"""Public headless overlay and precomputed MuJoCo replay APIs."""

from .overlay import (
    AxisPrimitive,
    LinePrimitive,
    OverlayFrame,
    SpherePrimitive,
    build_overlay,
    overlay_base_to_world,
)
from .replay import (
    SUPPORTED_PLAYBACK_METHODS,
    ComparisonRow,
    ReplayDisplayFrame,
    ReplayOptions,
    ReplaySequence,
    ReplayState,
    ReplayStep,
    TrailBuffer,
    build_replay_frames,
    format_frame_diagnostics,
    load_comparison_rows,
    prepare_replay_sequence,
    render_overlay_into_scene,
    replay_in_mujoco,
    validate_replay_consistency,
)

__all__ = [
    "SUPPORTED_PLAYBACK_METHODS",
    "AxisPrimitive",
    "ComparisonRow",
    "LinePrimitive",
    "OverlayFrame",
    "ReplayDisplayFrame",
    "ReplayOptions",
    "ReplaySequence",
    "ReplayState",
    "ReplayStep",
    "SpherePrimitive",
    "TrailBuffer",
    "build_overlay",
    "build_replay_frames",
    "format_frame_diagnostics",
    "load_comparison_rows",
    "overlay_base_to_world",
    "prepare_replay_sequence",
    "render_overlay_into_scene",
    "replay_in_mujoco",
    "validate_replay_consistency",
]
